# Generated by Django 4.2.7 on 2023-11-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_chair_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
