# Generated by Django 4.2.7 on 2023-11-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_chair_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url'),
        ),
    ]
