# Generated by Django 4.2.7 on 2023-12-05 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_chair_slug_alter_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chairs', to='location.location', verbose_name='میز'),
        ),
    ]
