# Generated by Django 4.2.7 on 2023-12-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockrecord',
            options={'verbose_name': 'انبارداری', 'verbose_name_plural': 'انبارداری ها'},
        ),
    ]
