# Generated by Django 4.2.7 on 2023-11-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'ایتم', 'verbose_name_plural': 'ایتم ها'},
        ),
    ]
