# Generated by Django 4.2.7 on 2023-11-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
